# version: '3'

services:
  sage:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=sage
      - POSTGRESQL_PASSWORD=sage
      - POSTGRESQL_DATABASE=sage

# docker container ls
# docker exec -it container_id psql -U sage -d sage
